import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#00685f',
        'primary-container': '#008378',
        'primary-fixed': '#89f5e7',
        'primary-fixed-dim': '#6bd8cb',
        'on-primary': '#ffffff',
        'on-primary-container': '#f4fffc',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#005049',
        secondary: '#006780',
        'secondary-container': '#76dcff',
        'secondary-fixed': '#b7eaff',
        'secondary-fixed-dim': '#6cd3f7',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#006077',
        'on-secondary-fixed': '#001f28',
        'on-secondary-fixed-variant': '#004e61',
        tertiary: '#b90538',
        'tertiary-container': '#dc2c4f',
        'tertiary-fixed': '#ffdadb',
        'tertiary-fixed-dim': '#ffb2b7',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#40000d',
        'on-tertiary-fixed-variant': '#92002a',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#006a61',
        background: '#f8f9fa',
        'on-surface': '#191c1d',
        'on-surface-variant': '#3d4947',
        'on-background': '#191c1d',
        outline: '#6d7a77',
        'outline-variant': '#bcc9c6',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#6bd8cb',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
        sm: '0.5rem',
      },
      fontFamily: {
        headline: ['var(--font-plus-jakarta)', 'var(--font-ibm-arabic)', 'sans-serif'],
        display: ['var(--font-plus-jakarta)', 'var(--font-ibm-arabic)', 'sans-serif'],
        body: ['var(--font-plus-jakarta)', 'var(--font-ibm-arabic)', 'sans-serif'],
        label: ['var(--font-plus-jakarta)', 'var(--font-ibm-arabic)', 'sans-serif'],
      },
      boxShadow: {
        ambient: '0 4px 24px rgba(0, 104, 95, 0.07)',
        'ambient-md': '0 8px 32px rgba(0, 104, 95, 0.10)',
        'ambient-sm': '0 2px 12px rgba(0, 0, 0, 0.04)',
      },
      backgroundImage: {
        'signature-gradient': 'linear-gradient(135deg, #00685f 0%, #006780 100%)',
      },
    },
  },
  plugins: [],
};

export default config;
